sudo: required
dist: trusty
#if: tag IS present

branches:
  only:
    - production

language: c

matrix:
  include:
    - os: osx
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

node_js:
  - 8.4

cache:
  directories:
    - node_modules

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - docker

install:
  - nvm install 8.4
  - npm install -g yarn
  - yarn install

before_script:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - yarn run production

script:
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then yarn run publish; else yarn run publish-docker; fi
